FROM registry.access.redhat.com/ubi9/go-toolset:1.20.10-6 as builder
ARG TARGETPLATFORM
COPY . .
USER 0
RUN mkdir -p /tmp/build/${TARGETPLATFORM}
COPY go.mod go.mod
COPY go.sum go.sum
RUN go mod download
RUN CGO_ENABLED=1 go build -o /tmp/build/${TARGETPLATFORM}/hyperdhcp main.go